name: Maven Package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch from GitHub
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build Maven project
        run: mvn -B package --file pom.xml -Dmaven.test.skip

      - name: Upload jar
        run: mkdir staging && cp target/sumpdata-*.jar staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
