name: Publish package to GitHub Packages
on:
  release:
    types: [created]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout main branch from GitHub
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21

      - name: Publish package
        run: mvn --batch-mode deploy -e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
